"""
Carve every pack_-touching statement out of docs/schema/dev_public_dump.sql
into docs/schema/pack_extracted.sql. Statement-aware (uses `;` as the
delimiter, not line-based) so multi-line CREATE TABLE / FUNCTION /
POLICY blocks come out whole.

Output ordering preserves the dump's ordering, which mostly follows
DDL dependency order from pg_dump.
"""
import re
from pathlib import Path

SRC = Path("docs/schema/dev_public_dump.sql")
DST = Path("docs/schema/pack_extracted.sql")

text = SRC.read_text()

# Split on bare ; at the end of a logical SQL statement. pg_dump emits
# each statement followed by `;\n\n\n` (or similar). Splitting on `;\n`
# is imperfect for dollar-quoted bodies but works in practice because
# pg_dump consistently terminates with `$$;\n` for those.
#
# Use a regex that splits on `;` followed by newline AND NOT preceded by
# being inside a $$ block. We track $$ count to handle that.

statements = []
buf = []
in_dollar = False
for line in text.splitlines(keepends=True):
    buf.append(line)
    # Toggle dollar-quote state on `$$` occurrences in this line.
    n_dollar = line.count("$$")
    if n_dollar % 2 == 1:
        in_dollar = not in_dollar
    if not in_dollar and line.rstrip().endswith(";"):
        statements.append("".join(buf))
        buf = []
if buf:
    statements.append("".join(buf))

print(f"Parsed {len(statements)} statements from {SRC}")

# Keep any statement that mentions a pack_ identifier (table, fn, etc.)
# Anchor on word boundary so we don't pick up unrelated like
# "backpack_" or attribute names.
pack_re = re.compile(r"\bpack_[a-z_]+", re.I)
pack_stmts = [s for s in statements if pack_re.search(s)]

print(f"  {len(pack_stmts)} statements mention pack_*")

# Strip ALTER ... OWNER TO postgres lines -- noise.
filtered = []
for s in pack_stmts:
    lines = [ln for ln in s.splitlines(keepends=True)
             if not re.match(r"^\s*ALTER (TABLE|FUNCTION|VIEW)\s+\"public\"\.\"pack_\w+\".*OWNER TO\b", ln, re.I)
             and not re.match(r"^\s*ALTER FUNCTION.*pack_.*OWNER TO\b", ln, re.I)]
    if lines:
        filtered.append("".join(lines))

DST.parent.mkdir(parents=True, exist_ok=True)
DST.write_text(
    "-- Pack module: every pack_-touching statement carved from\n"
    "-- docs/schema/dev_public_dump.sql in source order. Ownership\n"
    "-- (ALTER ... OWNER TO postgres) is stripped.\n"
    "-- Generated by scripts/carve_pack_from_dump.py -- do not hand-edit.\n\n"
    + "\n".join(filtered)
)
print(f"  Wrote {DST} ({DST.stat().st_size} bytes)")
