-- sales_pallet
-- ============
-- Physical pallet assembled for shipment. Sits between sales_po_fulfillment
-- (which lots fulfill which order lines) and sales_shipment_container
-- (the box the goods are loaded into). One row per pallet; line items
-- on the pallet live on sales_pallet_allocation.
--
-- The three-step shipping workflow writes here:
--   1. Palletize    — generate pallets, set pallet_type, capacity_utilization,
--                     pallet_number. Container assignment may be set here for
--                     pallets pre-routed by farm (cucumber pallets default to
--                     the cucumber container).
--   2. Stack        — assign container_space_number for non-Full pallets.
--                     Multiple Stackable pallets may share a space number.
--   3. Containerize — finalize sales_shipment_container_id, mark is_spillover
--                     where cucumber overflowed into lettuce/box.
--
-- After the run is finalized, operators bulk-set is_locked = true; subsequent
-- regenerations skip locked pallets so manual drag-and-drop assignments are
-- preserved when new POs come in.
--
-- The bin-packing logic (capacity-aware expansion, smart-split for Costco
-- KW/JW, spillover) lives in app code; this table is a passive store. The
-- algorithm is documented in org_business_rule (rule_type='Calculation' /
-- 'Workflow', module='sales').

CREATE TABLE IF NOT EXISTS sales_pallet (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id                      TEXT NOT NULL REFERENCES org(id),
    farm_id                     TEXT NOT NULL REFERENCES org_farm(id),

    -- Regeneration scope. Palletize/Stack/Containerize run for one
    -- (org, farm, target_invoice_date) at a time; locked rows in scope are
    -- preserved across re-runs, unlocked rows are wiped and rebuilt.
    target_invoice_date         DATE NOT NULL,

    pallet_number               TEXT NOT NULL,
    pallet_type                 TEXT NOT NULL CHECK (pallet_type IN ('Full', 'Shareable', 'Stackable')),

    -- 0..1 fraction of max_pallet capacity used. App enforces the labeling
    -- threshold (full_pallet) — values >= that threshold get pallet_type='Full'.
    capacity_utilization        NUMERIC NOT NULL DEFAULT 0 CHECK (capacity_utilization BETWEEN 0 AND 1),

    -- Container assignment — NULL until Containerize runs.
    sales_shipment_container_id UUID REFERENCES sales_shipment_container(id),

    -- Position within the container. NULL until Stack runs. Multiple
    -- Stackable pallets may share the same number when stacked. Bounded
    -- by sales_container_type.maximum_spaces of the container's type.
    container_space_number      INTEGER CHECK (container_space_number > 0),

    -- True when the pallet was reassigned out of its preferred container
    -- (cucumber pallets that overflowed into the lettuce or box-truck
    -- container). Surfaced in the UI for operator awareness.
    is_spillover                BOOLEAN NOT NULL DEFAULT false,

    -- Locked pallets are preserved on regenerate. Operators bulk-lock
    -- after a run is finalized.
    is_locked                   BOOLEAN NOT NULL DEFAULT false,

    notes                       TEXT,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                  TEXT,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by                  TEXT,
    is_deleted                  BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT uq_sales_pallet_number UNIQUE (org_id, target_invoice_date, pallet_number)
);

COMMENT ON TABLE sales_pallet IS 'Physical pallet assembled for shipment. Generated by the three-step Palletize/Stack/Containerize workflow scoped per (farm, target_invoice_date). Allocations from PO fulfillment lines live on sales_pallet_allocation. Locked pallets are preserved across regenerations.';

CREATE INDEX idx_sales_pallet_org           ON sales_pallet (org_id);
CREATE INDEX idx_sales_pallet_farm_date     ON sales_pallet (farm_id, target_invoice_date);
CREATE INDEX idx_sales_pallet_container     ON sales_pallet (sales_shipment_container_id);
CREATE INDEX idx_sales_pallet_unlocked_scope ON sales_pallet (org_id, farm_id, target_invoice_date)
    WHERE is_locked = false;

COMMENT ON COLUMN sales_pallet.target_invoice_date IS 'Invoice date the pallet was built for. Regeneration runs scoped to (farm_id, target_invoice_date) wipe unlocked pallets in scope and rebuild.';
COMMENT ON COLUMN sales_pallet.pallet_number IS 'CP01..CPnn (cucumber container), LP01..LPnn (lettuce container), BP01..BPnn (box truck), or {customer}_01..{customer}_10 for Shareable pallets.';
COMMENT ON COLUMN sales_pallet.pallet_type IS 'Full = at or above the product full_pallet threshold (no further allocations accepted). Shareable = mixed by customer; user can drag allocations between shareable pallets in the UI. Stackable = partial pallet that can be vertically stacked with another partial in one container space.';
COMMENT ON COLUMN sales_pallet.capacity_utilization IS 'Fraction 0..1 of product max_pallet used by the allocations on this pallet. Display as percentage in the UI.';
COMMENT ON COLUMN sales_pallet.sales_shipment_container_id IS 'Container the pallet ships in. NULL until Containerize runs. May not match the pallet''s preferred container when is_spillover=true.';
COMMENT ON COLUMN sales_pallet.container_space_number IS 'Position 1..N inside the container, where N = sales_container_type.maximum_spaces of the container''s type. Multiple Stackable pallets share a number when stacked.';
COMMENT ON COLUMN sales_pallet.is_spillover IS 'Pallet was overflowed out of its preferred container (e.g. cucumber pallet now in the lettuce container). Operator-visible flag.';
COMMENT ON COLUMN sales_pallet.is_locked IS 'When true, regeneration skips this pallet and its allocations. Operators bulk-lock after a run is finalized so subsequent runs preserve manual edits.';
